# Generated by Django 5.0.3 on 2024-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
